### ISSUE TITLE
Add requests to EXTERNAL_REQ_ALLOWLIST 

### ISSUE THREAD

**Issue by kasium** [typeshed-internal/stub_uploader#131]
Coming from https://github.com/typeshed-internal/stub_uploader/issues/90 it would be great to add requests to this list since it's needed to properly the recently added stubs for hvac. I guess it's a quite safe library to add (very common, no big dependencies beside urllib3, secure, ...)

**Comment by AlexWaygood** [comment]
`requests` doesn't have a `py.typed` file, so there wouldn't be much use adding it as a dependency for a stubs package. Can't you just add a dependency on `types-requests` instead (the stubs package typeshed distributes for `requests`)?

**Comment by kasium** [comment]
Valid point 😄
