### ISSUE TITLE
PEP 625 non-compliance of couple packages

### ISSUE THREAD

**Issue by ilevkivskyi** [typeshed-internal/stub_uploader#153]
Few hours ago typeshed-bot received couple emails with the following content

> This email is notifying you of an upcoming deprecation that we have determined may affect you as a result of your recent upload to 'types-setuptools'.
In the future, PyPI will require all newly uploaded source distribution filenames to comply with [PEP 625](https://peps.python.org/pep-0625/). Any source distributions already uploaded will remain in place as-is and do not need to be updated.
Specifically, your recent upload of types-setuptools-75.5.0.20241119.tar.gz is incompatible with PEP 625 because it does not contains the normalized project name 'types_setuptools'.
In most cases, this can be resolved by upgrading the version of your build tooling to a later version that supports PEP 625 and produces compliant filenames.
If you have questions, you can email [admin@pypi.org](mailto:admin@pypi.org) to communicate with the PyPI [admin@pypi.org](mailto:admin@pypi.org) to communicate with the PyPI administrators.

And a similar one for `types-tqdm`. I am not sure what changed, but this is probably something worth checking.

cc @JukkaL @srittau @JelleZijlstra

**Comment by AlexWaygood** [comment]
Triggered by https://github.com/pypi/warehouse/pull/17110, apparently

**Comment by JelleZijlstra** [comment]
Sounds like this would affect all our packages; we need to make sure the files are named with underscores instead of dashes.

**Comment by srittau** [comment]
Also, lower case only. See https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode for the normalization rules (and linked by [PEP 625](https://peps.python.org/pep-0625/#specification)).

**Comment by srittau** [comment]
Ironically, [canonicalize_name](https://packaging.pypa.io/en/stable/utils.html#packaging.utils.canonicalize_name) from `packaging` does not normalize according to these rules. But we might be able to use `canonicalize_name(...).replace("-", "_")`.

**Comment by srittau** [comment]
Ok, I've been using Python 3.12 locally while CI uses Python 3.11. When downgrading locally, the names are also wrong.

**Comment by ilevkivskyi** [comment]
> Ok, I've been using Python 3.12 locally while CI uses Python 3.11. When downgrading locally, the names are also wrong.

Hm, interesting. Does this mean we can fix the issue by simply bumping the version in CI? (But also ideally we should figure out what exactly happened)

**Comment by srittau** [comment]
It's probably due to this: https://setuptools.pypa.io/en/stable/history.html#id97.

Since setuptools isn't pre-installed with Python 3.12, the latest version is pulled, which includes the change, while this change is not yet in Python 3.11.
