### ISSUE TITLE
Also upload to test.pypi

### ISSUE THREAD

**Issue by nipunn1313** [typeshed-internal/stub_uploader#28]
Would it be possible/reasonable to also upload to test.pypi? I'm finding it hard to make use of test.pypi for my own packages.

For example - I run into this:
```
➜  mypy-protobuf git:(main) pip install -i https://test.pypi.org/simple/ mypy-protobuf==2.9
Looking in indexes: https://test.pypi.org/simple/
Collecting mypy-protobuf==2.9
  Downloading https://test-files.pythonhosted.org/packages/f6/25/ca55f61e50b6ec85614a09490dd43551890ad51c4a5ad1710991d9e0e0aa/mypy_protobuf-2.9-py3-none-any.whl (14 kB)
Collecting protobuf>=3.17.3
  Downloading https://test-files.pythonhosted.org/packages/74/4e/9f3cb458266ef5cdeaa1e72a90b9eda100e3d1803cbd7ec02f0846da83c3/protobuf-3.18.0-py2.py3-none-any.whl (174 kB)
     |████████████████████████████████| 174 kB 2.5 MB/s
ERROR: Could not find a version that satisfies the requirement types-protobuf>=3.17.3 (from mypy-protobuf) (from versions: none)
ERROR: No matching distribution found for types-protobuf>=3.17.3
```

Also open to alternate solutions to this issue.

**Comment by nipunn1313** [comment]
I can work around with 
```
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple mypy-protobuf==2.9
```

though it's not the command suggested on https://test.pypi.org/project/mypy-protobuf/2.9/

**Comment by ilevkivskyi** [comment]
I don't have a strong opinion on this, but TBH it is a quite rare case. I will defer the decision on this to other typeshed people.

**Comment by srittau** [comment]
I'm in Ivan's boat. I'd be ok with a PR that uploads selected stubs to test.pypi.org, as long as it doesn't become a maintenance burden.

**Comment by srittau** [comment]
I'm closing this for now. If someone submits a PR, we can consider this.
