### ISSUE TITLE
Please explicitly declare a licence to this repository

### ISSUE THREAD

**Issue by terceiro** [typeshed-internal/stub_uploader#31]
Hi,

I wanted to use some code from this repository for providing the typeshed stub packages in Debian. For that, I need to have specific licensing terms for ir. Anyone else wanting to reuse the code here also needs that, at least to do it legally.

**Comment by srittau** [comment]
@ilevkivskyi @nipunn1313 @hauntsaninja As contributors with non-trivial changes: Do you agree if we use the Apache License 2.0 that typeshed uses for your code?

**Comment by hauntsaninja** [comment]
Sure, whatever works for you works for me! Fwiw, I seem to remember typeshed is licensed under both Apache and MIT

**Comment by ilevkivskyi** [comment]
Apache license should be OK I think. Also cc @JukkaL for visibility.
